// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Question.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Question
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.06.02
// App/Edition: FAQ (Questions & Answers)/
// User:        2sic Web-Developer
// When:        2024-04-05 07:59:17Z
using System.Collections.Generic;
using ToSic.Sxc.Data;

namespace AppCode.Data
{
  // This is a generated class for Question 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Question data. <br/>
  /// Generated 2024-04-05 07:59:17Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Answer`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Question: AutoGenerated.ZagQuestion
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.Question in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagQuestion: Custom.Data.CustomItem
  {
    /// <summary>
    /// Answer as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Answer", scrubHtml: true) etc.
    /// </summary>
    public string Answer => _item.String("Answer", fallback: "");

    /// <summary>
    /// AnswerInnerContent as list of ITypedItem.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. 
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<ITypedItem> AnswerInnerContent => _answerInnerContent ??= _item.Children("AnswerInnerContent");
    private IEnumerable<ITypedItem> _answerInnerContent;

    /// <summary>
    /// Categories as list of Category.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type Category was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<Category> Categories => _categories ??= _item.Children<Category>("Categories");
    private IEnumerable<Category> _categories;

    /// <summary>
    /// Icon as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Icon", scrubHtml: true) etc.
    /// </summary>
    public string Icon => _item.String("Icon", fallback: "");

    /// <summary>
    /// InitiallyExpanded as bool. <br/>
    /// To get nullable use .Get("InitiallyExpanded") as bool?;
    /// </summary>
    public bool InitiallyExpanded => _item.Bool("InitiallyExpanded");

    /// <summary>
    /// InternalTitle as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("InternalTitle", scrubHtml: true) etc.
    /// </summary>
    public string InternalTitle => _item.String("InternalTitle", fallback: "");

    /// <summary>
    /// Priority as int. <br/>
    /// To get other types use methods such as .Decimal("Priority")
    /// </summary>
    public int Priority => _item.Int("Priority");

    /// <summary>
    /// Question as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Question", scrubHtml: true) etc.
    /// </summary>
    public string Question => _item.String("Question", fallback: "");
  }
}