// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "ViewConfiguration.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class ViewConfiguration
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.06.02
// App/Edition: FAQ (Questions & Answers)/
// User:        2sic Web-Developer
// When:        2024-04-05 07:59:17Z
using System.Collections.Generic;

namespace AppCode.Data
{
  // This is a generated class for ViewConfiguration 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// ViewConfiguration data. <br/>
  /// Generated 2024-04-05 07:59:17Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Categories`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class ViewConfiguration: AutoGenerated.ZagViewConfiguration
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.ViewConfiguration in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagViewConfiguration: Custom.Data.CustomItem
  {
    /// <summary>
    /// Categories as list of Category.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type Category was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<Category> Categories => _categories ??= _item.Children<Category>("Categories");
    private IEnumerable<Category> _categories;

    /// <summary>
    /// SortField as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SortField", scrubHtml: true) etc.
    /// </summary>
    public string SortField => _item.String("SortField", fallback: "");

    /// <summary>
    /// SortOrder as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SortOrder", scrubHtml: true) etc.
    /// </summary>
    public string SortOrder => _item.String("SortOrder", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}